### ISSUE TITLE
想添加分项目的功能或者插件，求建议

### ISSUE THREAD

**Issue by qq492607291** [easychen/TeamToy#24]
发现在 http://tt2net.sinaapp.com/?c=ticket&a=my 的过了三个月没人管。qq群，申请了没被加入群。微博私信也不见回应。故到这里请教一下，望见谅。

因为实际工作中是多个项目并行的，在不同项目中角色可能也不同。如何在一个teamtoy系统中使用哪？除非被授权，否则不能访问自己未参与的项目的信息，甚至不能看到其他项目的成员。

请教，上面的需求如何设计实现比较好？能否给点建议和思路，准备尝试实现一下。

**Comment by easychen** [comment]
TeamToy本身是为充分授权的扁平结构设计的，调整起来比较麻烦。一般通过架设多个teamtoy来解决这个问题。
