### ISSUE TITLE
API调用错误，请稍后再试。错误号100002 错误信息 can not save data

### ISSUE THREAD

**Issue by charleslei** [easychen/TeamToy#5]
API调用错误，请稍后再试。错误号100002 错误信息 can not save data

亲改改呗，别人转给我的任务，点击子任务就成这样了

**Comment by easychen** [comment]
这个问题修复过啊，你的版本是？

**Comment by charleslei** [comment]
TeamToy V1855 

superwanderman

发件人： Easy
发送时间： 2013-03-12 12:13
收件人： easychen/TeamToy
抄送： charleslei
主题： Re: [TeamToy] API调用错误，请稍后再试。错误号100002 错误信息 can not save data (#5)
这个问题修复过啊，你的版本是？

**Comment by easychen** [comment]
已经修复过该问题。新创建的checklist应该正常了。

**Comment by charleslei** [comment]
好的，谢谢。

superwanderman

发件人： Easy
发送时间： 2013-03-20 17:12
收件人： easychen/TeamToy
抄送： charleslei
主题： Re: [TeamToy] API调用错误，请稍后再试。错误号100002 错误信息 can not save data (#5)
已经修复过该问题。新创建的checklist应该正常了。
