### ISSUE TITLE
在chrome浏览器下，接受聊天信息会重复提示和重复显示

### ISSUE THREAD

**Issue by chyblog** [easychen/TeamToy#9]
在chrome浏览器下，接受聊天信息会重复提示和重复显示。
导致聊天工具无法正常使用。

火狐浏览器没有问题

==add 2013-03-28 13:16==
我试了几个版本的teamtoy，都有这个问题。猜想可能跟登录的时候加载历史的聊天记录有关系，当历史记录比较多的时候，在chorme和ie10浏览器（修改过您的代码，IE10可以用了，但还是有些使用问题），都会重复提示和显示消息。

**Comment by easychen** [comment]
该问题在测试浏览器上未能重现，请清除缓存，关闭插件再试试。

**Comment by chyblog** [comment]
这个问题已经临时解决了，我把所有聊天记录都删除了，就好了。不过聊天记录多了，chrome上还是有问题。联系过互助群的管理员，他也能够重现 

------------------ Original ------------------
From: "Easy"; 
Date: 2013年3月27日(星期三) 下午3:42
To: "easychen/TeamToy"; 
Cc: "chyblog"; 
Subject: Re: [TeamToy] 在chrome浏览器下，接受聊天信息会重复提示和重复显示 (#9)

该问题在测试浏览器上未能重现，请清除缓存，关闭插件再试试。
